Format:
  Delimited:
    chrom1_field: "chr"
    chrom2_field: "chr"
    bin1_field: "bin1"
    bin2_field: "bin2"
    main_value_field: "rescaled_intensity"
    optional_field: ["RawCount"]
    delimiter: "\t"
    resolution: 5000
  Cooler:
    main_value_field: "Default"
    optional_field: ["Count", "KR", "VC", "VC_SQRT"]
    resolution: 5000
    chromosomes: "chr22"
Metadata:
  data: "/mnt/s/workspace/hic_datasets/GM12878_example.mcool"
  version:
  resolution: 5000
  assembly: hg38
  optional: